import React from "react";
import Document, { Head, Main, NextScript, Html } from "next/document";
import { ServerStyleSheet } from "styled-components";

// @ts-ignore
export default class MyDocument extends Document {
  static async getInitialProps(ctx: any) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App: any) => (props: any) =>
            sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);

      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
    } finally {
      sheet.seal();
    }
  }

  render() {
    return (
      <Html lang='en'>
        <meta name='theme-color' content='#f9f8fa' />
        <meta charSet='utf-8' />
        {/* Use minimum-scale=1 to enable GPU rasterization */}
        <meta
          name='viewport'
          content='minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, minimal-ui'
        />
        <Head>
          {/* PWA primary color */}
          <title>Model UK - UtterBerry</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='shortcut icon' href={`/img/utterberry-icon.svg`} />
          <link
            href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Rokkitt:600&display=swap'
            rel='stylesheet'
          />
        </Head>
        <body
          style={{
            margin: 0,
          }}
        >
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
